name: Build C++ EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile Chatbot
        run: g++ -static main.cpp -o my_chatbot.exe
      
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: chatbot-download
          path: my_chatbot.exe   
